 
import "oaidl.idl";
import "ocidl.idl";

#include "DecoratorConfig.h"

import "Gme.idl";
import "Core.idl";
[
	uuid(TYPELIB_UUID),
	version(1.0),
	helpstring("TYPELIB_NAME")
]
library DecoratorLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	importlib("..\Core\CoreLib.tlb");
	importlib("..\Meta\MetaLib.tlb");
	importlib("..\Mga\MgaLib.tlb");
	importlib("..\Gme\GmeLib.tlb");

	[
		uuid(COCLASS_UUID),
		helpstring(COCLASS_NAME)
	]
	coclass AnnotatorDecorator
	{
		[default] interface IMgaElementDecorator;
		interface IGMEVersionInfo;
	};

};
