///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type
#define RAWCOMPONENT

// COM UUID-s, names and progID
#define TYPELIB_UUID "4076E160-848F-4825-981E-C30FE93684BE"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (MetaMAid)"
#define COCLASS_UUID "7CA2C750-5420-427B-9E9F-3333DF6427AA"
#define COCLASS_NAME "MGA Interpreter CoClass (MetaMAid)"
#define COCLASS_PROGID "MGA.Interpreter.MetaMAid"

#define COCLASS_UUID_EXPLODED1  0x7ca2c750
#define COCLASS_UUID_EXPLODED2   0x5420
#define COCLASS_UUID_EXPLODED3   0x427b
#define COCLASS_UUID_EXPLODED4   0x9e
#define COCLASS_UUID_EXPLODED5   0x9f
#define COCLASS_UUID_EXPLODED6   0x33
#define COCLASS_UUID_EXPLODED7   0x33
#define COCLASS_UUID_EXPLODED8   0xdf
#define COCLASS_UUID_EXPLODED9   0x64
#define COCLASS_UUID_EXPLODED10  0x27
#define COCLASS_UUID_EXPLODED11  0xaa


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME "MetaMAid"


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT "MetaMAid AddOn"

// This macro determines the component type (addon vs. interpreter):
#define GME_ADDON
#define ADDON_EVENTMASK 0x80000000

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGMS "MetaGME"


// not defined: #define BON_ICON_SUPPORT

// not defined: #define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
