///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type
#define BON2COMPONENT

// COM UUID-s, names and progID
#define TYPELIB_UUID "BD75CE5A-59A3-4F51-B171-87AB7EAC267D"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (MONTraverser)"
#define COCLASS_UUID "137C4461-FC38-4813-AC39-A6F194FEEB2D"
#define COCLASS_NAME "MGA Interpreter CoClass (MONTraverser)"
#define COCLASS_PROGID "MGA.Interpreter.MONTraverser"

#define COCLASS_UUID_EXPLODED1  0x137c4461
#define COCLASS_UUID_EXPLODED2   0xfc38
#define COCLASS_UUID_EXPLODED3   0x4813
#define COCLASS_UUID_EXPLODED4   0xac
#define COCLASS_UUID_EXPLODED5   0x39
#define COCLASS_UUID_EXPLODED6   0xa6
#define COCLASS_UUID_EXPLODED7   0xf1
#define COCLASS_UUID_EXPLODED8   0x94
#define COCLASS_UUID_EXPLODED9   0xfe
#define COCLASS_UUID_EXPLODED10  0xeb
#define COCLASS_UUID_EXPLODED11  0x2d


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME "MONTraverser"


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT "MONTraverser Interpreter"

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGM_INDEPENDENT


#define BON_ICON_SUPPORT

// not defined: #define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
