
import "oaidl.idl";
import "ocidl.idl";


//--------------------------------------------------------------------------------------------
// --------------------------- Meta Library
import "Mga.idl";
import "Gme.idl";



[
	uuid(0ADEEC71-D83A-11D3-B36B-005004CC8592),
	version(1.0),
	helpstring("GME Type Library")
]
library GmeLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	struct CustomPathData;

	//  Class information for CMgaDataSource
	[ uuid(FCB7DB63-9F59-46a6-9FEF-5C2679AEA69A) ]
	coclass MgaDataSource
	{
		[default] interface IMgaDataSource;
		interface ISupportErrorInfo;
	};

	//  Class information for CGMEOLEApp

	[ uuid(C7DCCC2E-1642-4a40-8060-51A7B9FAE488) ]
	coclass Application
	{
		[default] interface IGMEOLEApp;
		[source]  interface IMgaComponent;
		[source]  interface IMgaComponentEx;
		interface IMgaVersionInfo;
		interface ISupportErrorInfo;
	};

	//  Class information for CGMEOLEIt

	[ uuid(A19756E1-56AB-4ae5-974A-B3766E190697) ]
	coclass It
	{
		[default] interface IGMEOLEIt;
		interface ISupportErrorInfo;
	};

	//  Class information for CGMEOLEModel

	[ uuid(7B512D6A-6767-4e3f-BF1F-A22943E68C32) ]
	coclass Model
	{
		[default] interface IGMEOLEModel;
		interface ISupportErrorInfo;
	};

	//  Class information for CGMEOLEAspect

	[ uuid(D4AFDD5A-037A-42d5-A9A1-F44C81EA7AF7) ]
	coclass Aspect
	{
		[default] interface IGMEOLEAspect;
		interface ISupportErrorInfo;
	};


	//  Class information for CGMEOLEPanel

	[ uuid(A946466F-29E2-44a6-A69A-4D6D9268A37F) ]
	coclass Panel
	{
		[default] interface IGMEOLEPanel;
		interface ISupportErrorInfo;
	};

	//  Class information for CGMEOLEPanel

	[ uuid(05403CF4-5C53-49d4-8F63-ED37870ABF1F) ]
	coclass Collection
	{
		[default] interface IGMEOLEColl;
		interface ISupportErrorInfo;
	};

	[
		uuid(DA19317A-4CDE-4331-98E7-9DF0DC04DF1E),
		helpstring("AutoRouterPort Class")
	]
	coclass AutoRouterPort
	{
		[default] interface IAutoRouterPort;
	};

	[
		uuid(7ED29520-4A10-4411-B91C-D75B6ED303F4),
		helpstring("AutoRouterBox Class")
	]
	coclass AutoRouterBox
	{
		[default] interface IAutoRouterBox;
	};

	[
		uuid(37CBF476-97B8-4365-BFCD-8C331E16B713),
		helpstring("AutoRouterGraph Class")
	]
	coclass AutoRouterGraph
	{
		[default] interface IAutoRouterGraph;
	};

	[
		uuid(8B81AE9D-482F-4A2F-815F-E9F990BBD3C4),
		helpstring("AutoRouterPath Class")
	]
	coclass AutoRouterPath
	{
		[default] interface IAutoRouterPath;
	};
};
