
import "oaidl.idl";
import "ocidl.idl";

import "Parser.idl";
import "Core.idl";


// --------------------------- Parser Library

[
	uuid(70C41B15-E3CE-11D3-B37A-005004D38590),
	version(1.0),
	helpstring("MGA Parser Type Library")
]
library PARSERLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	importlib("..\Core\CoreLib.tlb");
	importlib("..\Meta\MetaLib.tlb");
	importlib("..\Mga\MgaLib.tlb");

	[
		uuid(70C41B25-E3CE-11D3-B37A-005004D38590),
		helpstring("MgaMetaParser Class")
	]
	coclass MgaMetaParser
	{
		[default] interface IMgaMetaParser;
		interface ISupportErrorInfo;
		interface IGMEVersionInfo;
	};

	[
		uuid(A5D0DAE7-16EE-11D4-B3C2-005004D38590),
		helpstring("MgaDumper Class")
	]
	coclass MgaDumper
	{
		[default] interface IMgaDumper;
		interface IGMEVersionInfo;
	};

	[
		uuid(94D6FB54-1F7C-11D4-B3D0-005004D38590),
		helpstring("MgaParser Class")
	]
	coclass MgaParser
	{
		[default] interface IMgaParser;
		interface IGMEVersionInfo;
	};

};
