///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type
#define RAWCOMPONENT

// COM UUID-s, names and progID
#define TYPELIB_UUID "CB1A903F-7E16-4F08-BF62-A32906EC28E4"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (GMEMerge)"
#define COCLASS_UUID "ACD781EC-472D-47EE-BB0D-BDA9C12B984B"
#define COCLASS_NAME "MGA Interpreter CoClass (GMEMerge)"
#define COCLASS_PROGID "MGA.Interpreter.GMEMerge"

#define COCLASS_UUID_EXPLODED1  0xacd781ec
#define COCLASS_UUID_EXPLODED2   0x472d
#define COCLASS_UUID_EXPLODED3   0x47ee
#define COCLASS_UUID_EXPLODED4   0xbb
#define COCLASS_UUID_EXPLODED5   0xd
#define COCLASS_UUID_EXPLODED6   0xbd
#define COCLASS_UUID_EXPLODED7   0xa9
#define COCLASS_UUID_EXPLODED8   0xc1
#define COCLASS_UUID_EXPLODED9   0x2b
#define COCLASS_UUID_EXPLODED10  0x98
#define COCLASS_UUID_EXPLODED11  0x4b


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME "GMEMerge"


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT "GMEMerge Interpreter"

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGM_INDEPENDENT


#define BON_ICON_SUPPORT

// not defined: #define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
