 
import "oaidl.idl";
import "ocidl.idl";

import "meta.idl";
import "mga.idl";
import "mgautil.idl";
import "gme.idl";
import "MgaDecorator.idl";


[
	uuid(61F92723-01CB-427c-AE6F-C9FA6A857166),
	version(1.0),
	helpstring("DECORATORLibLib 1.0 Type Library")
]
library DECORATORLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
};