///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type
#define RAWCOMPONENT

// COM UUID-s, names and progID
#define TYPELIB_UUID "021E6940-0C8D-4391-9BF0-38956359D63C"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (QuRep)"
#define COCLASS_UUID "9101B5C0-4895-4439-911E-315E99670371"
#define COCLASS_NAME "MGA Interpreter CoClass (QuRep)"
#define COCLASS_PROGID "MGA.Interpreter.QuRep"

#define COCLASS_UUID_EXPLODED1  0x9101b5c0
#define COCLASS_UUID_EXPLODED2   0x4895
#define COCLASS_UUID_EXPLODED3   0x4439
#define COCLASS_UUID_EXPLODED4   0x91
#define COCLASS_UUID_EXPLODED5   0x1e
#define COCLASS_UUID_EXPLODED6   0x31
#define COCLASS_UUID_EXPLODED7   0x5e
#define COCLASS_UUID_EXPLODED8   0x99
#define COCLASS_UUID_EXPLODED9   0x67
#define COCLASS_UUID_EXPLODED10  0x3
#define COCLASS_UUID_EXPLODED11  0x71


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME "QuRep"


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT "QuickReplace Interpreter"

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGMS "MetaGME"


#define BON_ICON_SUPPORT

// not defined: #define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
