
// This file will be processed by the MIDL compiler to produce the
// type library (ComponentLib.tlb).

#include <ComponentConfig.h>

#include <InterfaceColl.h>
#include <meta.idl>
#include <mga.idl>
#include <mgautil.idl>
#include <gme.idl>
#include <parser.idl>


[
	uuid(TYPELIB_UUID),
	version(1.0),
	helpstring(TYPELIB_NAME)
]
library MgaComponentLib
{
	importlib("stdole32.tlb");

	[
		// you have to copy this GUID to the ComponentObj.cpp,

		uuid(COCLASS_UUID),
		helpstring(COCLASS_NAME)
	]
	coclass MgaComponent
	{
		[default] interface IMgaComponentEx;
		interface IMgaComponent;
		interface IMgaVersionInfo;
	};
};


